### PR TITLE
Add replacement banner graphic

### PR DESCRIPTION
**Pull request by insectengine**
Add replacement banner graphic for new readme

### CODE REVIEW

**Comment by gastaldi** [comment]
Who can review and merge this? @maxandersen ?

**Comment by gsmet** [comment]
I'm not sure it's a good idea to use design.jboss.org for that, especially for a ~2MB image. It's really slow.

**Comment by insectengine** [comment]
@gsmet - I created an image fold in the project and added it there. This better?

**Review by gsmet — APPROVED** [review]

**Comment by gsmet** [comment]
Yep, thanks!

**Comment by gsmet** [comment]
I had some fun figuring out how to fix the image path but now it's all good.

**Pull request merged**
